In [1]:
import os
os.environ["OMP_NUM_THREADS"]="3"

In [2]:
import torch
from torch.utils.data import DataLoader
from torchvision import transforms
from torchvision.datasets import ImageFolder
from CNN_model import VGG
import numpy as np

import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec

%matplotlib inline
plt.rcParams['figure.figsize'] = (10.0, 8.0) # set default size of plots
plt.rcParams['image.interpolation'] = 'nearest'
plt.rcParams['image.cmap'] = 'gray'

%load_ext autoreload
%autoreload 2

In [4]:
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

# Data loading: Celeb A Dataset

In [5]:
batch_size = 12
scale_size = 64  # Change size in CNN_model as well

celeba_root = 'Data'

In [6]:
#transforms
normalize = transforms.Normalize(mean=[0.485, 0.456, 0.406],
                                 std=[0.229, 0.224, 0.225])

celeba_train = ImageFolder(root=celeba_root, transform=transforms.Compose([
  #transforms.Normalize(mean=[0.485, 0.456, 0.406],
                                 #std=[0.229, 0.224, 0.225]),
  transforms.Resize(scale_size),
  transforms.ToTensor()
]))

celeba_loader_train = DataLoader(celeba_train, batch_size=batch_size, drop_last=True, shuffle=True,dataset_file="celeba_data/list_attr_celeba.csv")

# Visualize dataset

# Training 


In [7]:
NUM_EPOCHS = 50
learning_rate = 0.0002

In [8]:
#send models to device
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
model = VGG().to(device)

In [9]:
#set optimizer
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate, betas = (0.5, 0.999))
#set loss
loss = torch.nn.BCEWithLogitsLoss()


In [12]:
# train model
for epochs in range(NUM_EPOCHS):
    for i, (images, target) in enumerate(celeba_loader_train):
        print(i)
        print(target)

0
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
1
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
2
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
3
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
4
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
5
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
6
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
7
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
8
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
9
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
10
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
11
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
12
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
13
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
14
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
15
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
16
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
17
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
18
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
19
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
20
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
21

KeyboardInterrupt: 

In [17]:
print(sample[0])

124
